version: 2

project_name: gomodoro

before:
  hooks:
    - go mod tidy

builds:
  - id: gomodoro
    main: ./cmd/gomodoro
    binary: gomodoro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: gomodoro
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: oadultradeepfield
    name: gomodoro
  draft: false
  prerelease: auto
